package ru.maksonic.beresta.ui.theme.color.palette

import ru.maksonic.beresta.ui.theme.color.AppColor
import ru.maksonic.beresta.ui.theme.color.Palette

/**
 * @Author maksonic on 25.02.2023
 */
val baseLightPalette = AppColor(
    primary = Palette.azureRadiance,
    onPrimary = Palette.white,
    primaryContainer = Palette.white,
    onPrimaryContainer = Palette.black,
    secondary = Palette.doveGray,
    onSecondary = Palette.black,
    secondaryContainer = Palette.black,
    onSecondaryContainer = Palette.black,
    tertiary = Palette.chineseSilver,
    onTertiary = Palette.nero,
    tertiaryContainer = Palette.antiFlashWhite,
    onTertiaryContainer = Palette.lightSilver,
    error = Palette.carmineRed,
    onError = Palette.carmineRed,
    errorContainer = Palette.carmineRed,
    onErrorContainer = Palette.carmineRed,
    background = Palette.snow,
    onBackground = Palette.nero,
    surface = Palette.white,
    onSurface = Palette.frenchPassLight,
    surfaceVariant = Palette.platinum,
    onSurfaceVariant = Palette.solitude,
    outline = Palette.carmineRed,
    shadow = Palette.black,
    scrim = Palette.black.copy(alpha = 0.24f),
    transparent = Palette.transparent,
    idle = Palette.azureRadiance,
    black = Palette.black,
    blue = Palette.azureRadiance,
    green = Palette.electricGreen,
    purple = Palette.electricViolet,
    red = Palette.coralRed,
    orange = Palette.vividGamboge,
    yellow = Palette.bananaYellow,
)

val baseDarkPalette = AppColor(
    primary = Palette.anakiwa,
    onPrimary = Palette.black,
    primaryContainer = Palette.mineShaft,
    onPrimaryContainer = Palette.snow,
    secondary = Palette.gray,
    onSecondary = Palette.white,
    secondaryContainer = Palette.doveGray,
    onSecondaryContainer = Palette.gray,
    tertiary = Palette.doveGray,
    onTertiary = Palette.white,
    tertiaryContainer = Palette.tundora,
    onTertiaryContainer = Palette.doveGray,
    error = Palette.carmineRed,
    onError = Palette.carmineRed,
    errorContainer = Palette.carmineRed,
    onErrorContainer = Palette.carmineRed,
    background = Palette.nero,
    onBackground = Palette.snow,
    surface = Palette.mineShaft,
    onSurface = Palette.tundora,
    surfaceVariant = Palette.tundora,
    onSurfaceVariant = Palette.tundora,
    outline = Palette.carmineRed,
    shadow = Palette.black,
    scrim = Palette.black.copy(alpha = 0.32f),
    transparent = Palette.transparent,
    idle = Palette.azureRadiance,
    black = Palette.nero,
    blue = Palette.anakiwa,
    green = Palette.mintGreen,
    purple = Palette.paleViolet,
    red = Palette.roseBud,
    orange = Palette.peachOrange,
    yellow = Palette.pastelYellow,
)


val highContrastPalette = AppColor(
    primary = Palette.azureRadiance,
    onPrimary = Palette.black,
    primaryContainer = Palette.nero,
    onPrimaryContainer = Palette.white,
    secondary = Palette.gray,
    onSecondary = Palette.white,
    secondaryContainer = Palette.doveGray,
    onSecondaryContainer = Palette.gray,
    tertiary = Palette.doveGray,
    onTertiary = Palette.white,
    tertiaryContainer = Palette.black,
    onTertiaryContainer = Palette.mineShaft,
    error = Palette.carmineRed,
    onError = Palette.carmineRed,
    errorContainer = Palette.carmineRed,
    onErrorContainer = Palette.carmineRed,
    background = Palette.black,
    onBackground = Palette.white,
    surface = Palette.black,
    onSurface = Palette.doveGray,
    surfaceVariant = Palette.mineShaft,
    onSurfaceVariant = Palette.tundora,
    outline = Palette.carmineRed,
    shadow = Palette.black,
    scrim = Palette.black.copy(alpha = 0.8f),
    transparent = Palette.transparent,
    idle = Palette.azureRadiance,
    black = Palette.mineShaft,
    blue = Palette.azureRadiance,
    green = Palette.electricGreen,
    purple = Palette.electricViolet,
    red = Palette.coralRed,
    orange = Palette.vividGamboge,
    yellow = Palette.bananaYellow,
)
