package ru.maksonic.beresta.ui.theme.color.app_palette

import ru.maksonic.beresta.ui.theme.color.color_palette.Palette
import ru.maksonic.beresta.ui.theme.color.PlaceholderColors
import ru.maksonic.beresta.ui.theme.color.color_palette.PaletteImageComponent
import ru.maksonic.beresta.ui.theme.color.color_palette.ImagePalette

/**
 * @Author maksonic on 25.02.2023
 */
val filledLightOrangePalette = baseLightPalette.copy(
    primary = Palette.Orange.vividGamboge,
    onPrimary = Palette.Orange.mustardBrown,
    onPrimaryContainer = Palette.Orange.cola,
    secondary = Palette.Yellow.lemonChiffon,
    onSecondary = Palette.Orange.cola,
    secondaryContainer = Palette.Orange.serenade,
    onSecondaryContainer = Palette.Orange.frangipane,
    tertiary = Palette.Yellow.blond,
    onTertiary = Palette.Orange.mustardBrown,
    tertiaryContainer = Palette.Orange.mustardBrown,
    onTertiaryContainer = Palette.white,
    background = Palette.Orange.bridalHeath,
    surface = Palette.Orange.bridalHeath,
    onSurface = Palette.Orange.mustardBrown,
    surfaceVariant = Palette.Orange.blanchedAlmond,
    onSurfaceVariant = Palette.Orange.frangipane,
    inverseSurface = Palette.Orange.mustardBrown,
    inversePrimary = Palette.Yellow.pastelYellow,
    surfaceTint = Palette.Orange.vividGamboge,
    outlineVariant = Palette.Orange.serenade,
    onSnack = Palette.Orange.peachOrange,
    placeholderColors = PlaceholderColors(
        c0 = ImagePalette.Orange.Light.c0,
        c1 = ImagePalette.Orange.Light.c1,
        c2 = ImagePalette.Orange.Light.c2,
        c3 = ImagePalette.Orange.Light.c3,
        c4 = ImagePalette.Orange.Light.c4,
        f0 = PaletteImageComponent.Folder.Light.f0,
        f1 = PaletteImageComponent.Folder.Light.f1,
        f2 = PaletteImageComponent.Folder.Light.f2,
        f3 = PaletteImageComponent.Folder.Light.f3,
        t0 = PaletteImageComponent.Trash.Light.t0,
        t1 = PaletteImageComponent.Trash.Light.t1,
        t2 = PaletteImageComponent.Trash.Light.t2,
        t3 = PaletteImageComponent.Trash.Light.t3,
        s0 = PaletteImageComponent.Search.Light.s0,
        s1 = PaletteImageComponent.Search.Light.s1,
        s2 = PaletteImageComponent.Search.Light.s2,
        s3 = PaletteImageComponent.Search.Light.s3,
    )
)
val filledDarkOrangePalette = baseDarkPalette.copy(
    primary = Palette.Orange.x0,
    onPrimary = Palette.Orange.x0,
    primaryContainer = Palette.Orange.x2,
    onPrimaryContainer = Palette.white,
    secondary = Palette.Orange.x4,
    onSecondary = Palette.white,
    secondaryContainer = Palette.Orange.x2,
    onSecondaryContainer = Palette.Orange.x5,
    tertiary = Palette.Orange.x5,
    onTertiary = Palette.white,
    tertiaryContainer = Palette.Orange.x0,
    onTertiaryContainer = Palette.Orange.x1,
    background = Palette.Orange.x1,
    surface = Palette.Orange.x1,
    surfaceVariant = Palette.Orange.x3,
    onSurfaceVariant = Palette.Orange.x4,
    surfaceTint = Palette.black,
    inverseOnSurface = Palette.Orange.x4,
    inversePrimary = Palette.Orange.x5,
    outlineVariant = Palette.Orange.x3,
    snack = Palette.Orange.cola,
    onSnack = Palette.Orange.peachOrange,
    onSnackContainer = Palette.white,
    placeholderColors = PlaceholderColors(
        c0 = ImagePalette.Orange.Dark.Fill.c0,
        c1 = ImagePalette.Orange.Dark.Fill.c1,
        c2 = ImagePalette.Orange.Dark.Fill.c2,
        c3 = ImagePalette.Orange.Dark.Fill.c3,
        c4 = ImagePalette.Orange.Dark.Fill.c4,
        f0 = PaletteImageComponent.Folder.Dark.f0,
        f1 = PaletteImageComponent.Folder.Dark.f1,
        f2 = PaletteImageComponent.Folder.Dark.f2,
        f3 = PaletteImageComponent.Folder.Dark.f3,
        t0 = PaletteImageComponent.Trash.Dark.t0,
        t1 = PaletteImageComponent.Trash.Dark.t1,
        t2 = PaletteImageComponent.Trash.Dark.t2,
        t3 = PaletteImageComponent.Trash.Dark.t3,
        s0 = PaletteImageComponent.Search.Dark.s0,
        s1 = PaletteImageComponent.Search.Dark.s1,
        s2 = PaletteImageComponent.Search.Dark.s2,
        s3 = PaletteImageComponent.Search.Dark.s3,
    )
)
val outlinedLightOrangePalette = baseLightPalette.copy(
    onPrimary = Palette.Orange.mustardBrown,
    onTertiary = Palette.Orange.mustardBrown,
    tertiaryContainer = Palette.Orange.vividGamboge,
    onTertiaryContainer = Palette.white,
    inversePrimary = Palette.Yellow.pastelYellow,
    primary = Palette.Orange.vividGamboge,
    onSnack = Palette.Orange.peachOrange,
    placeholderColors = PlaceholderColors(
        c0 = ImagePalette.Orange.Light.c0,
        c1 = ImagePalette.Orange.Light.c1,
        c2 = ImagePalette.Orange.Light.c2,
        c3 = ImagePalette.Orange.Light.c3,
        c4 = ImagePalette.Orange.Light.c4,
        f0 = PaletteImageComponent.Folder.Light.f0,
        f1 = PaletteImageComponent.Folder.Light.f1,
        f2 = PaletteImageComponent.Folder.Light.f2,
        f3 = PaletteImageComponent.Folder.Light.f3,
        t0 = PaletteImageComponent.Trash.Light.t0,
        t1 = PaletteImageComponent.Trash.Light.t1,
        t2 = PaletteImageComponent.Trash.Light.t2,
        t3 = PaletteImageComponent.Trash.Light.t3,
        s0 = PaletteImageComponent.Search.Light.s0,
        s1 = PaletteImageComponent.Search.Light.s1,
        s2 = PaletteImageComponent.Search.Light.s2,
        s3 = PaletteImageComponent.Search.Light.s3,
    )
)
val outlinedDarkOrangePalette = baseDarkPalette.copy(
    primary = Palette.Orange.peachOrange,
    tertiaryContainer = Palette.Orange.peachOrange,
    onPrimary = Palette.Orange.peachOrange,
    onSnack = Palette.Orange.mustardBrown,
    placeholderColors = PlaceholderColors(
        c0 = ImagePalette.Orange.Dark.c0,
        c1 = ImagePalette.Orange.Dark.c1,
        c2 = ImagePalette.Orange.Dark.c2,
        c3 = ImagePalette.Orange.Dark.c3,
        c4 = ImagePalette.Orange.Dark.c4,
        f0 = PaletteImageComponent.Folder.Dark.f0,
        f1 = PaletteImageComponent.Folder.Dark.f1,
        f2 = PaletteImageComponent.Folder.Dark.f2,
        f3 = PaletteImageComponent.Folder.Dark.f3,
        t0 = PaletteImageComponent.Trash.Dark.t0,
        t1 = PaletteImageComponent.Trash.Dark.t1,
        t2 = PaletteImageComponent.Trash.Dark.t2,
        t3 = PaletteImageComponent.Trash.Dark.t3,
        s0 = PaletteImageComponent.Search.Dark.s0,
        s1 = PaletteImageComponent.Search.Dark.s1,
        s2 = PaletteImageComponent.Search.Dark.s2,
        s3 = PaletteImageComponent.Search.Dark.s3,
    )
)
val highContrastOrangePalette = highContrastPalette.copy(
    primary = Palette.Orange.vividGamboge,
    tertiaryContainer = Palette.Orange.vividGamboge,
    onPrimary = Palette.Orange.vividGamboge,
    onSnack = Palette.Orange.mustardBrown,
    placeholderColors = PlaceholderColors(
        c0 = ImagePalette.Orange.Dark.c0,
        c1 = ImagePalette.Orange.Dark.c1,
        c2 = ImagePalette.Orange.Dark.c2,
        c3 = ImagePalette.Orange.Dark.c3,
        c4 = ImagePalette.Orange.Dark.c4,
        f0 = PaletteImageComponent.Folder.Dark.f0,
        f1 = PaletteImageComponent.Folder.Dark.f1,
        f2 = PaletteImageComponent.Folder.Dark.f2,
        f3 = PaletteImageComponent.Folder.Dark.f3,
        t0 = PaletteImageComponent.Trash.Dark.t0,
        t1 = PaletteImageComponent.Trash.Dark.t1,
        t2 = PaletteImageComponent.Trash.Dark.t2,
        t3 = PaletteImageComponent.Trash.Dark.t3,
        s0 = PaletteImageComponent.Search.Dark.s0,
        s1 = PaletteImageComponent.Search.Dark.s1,
        s2 = PaletteImageComponent.Search.Dark.s2,
        s3 = PaletteImageComponent.Search.Dark.s3,
    )
)